sudo: required
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl

  - openssl aes-256-cbc -K $encrypted_24b326dcdb79_key -iv $encrypted_24b326dcdb79_iv -in service-account.json.enc -out service-account.json -d
  - gcloud auth activate-service-account --key-file service-account.json

  - gcloud config set project halogen-trilogy-239613
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials microservices-cluster
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t liketurbo/react-test -f ./packages/web/Dockerfile.dev ./packages/web
script:
  - docker run liketurbo/react-test yarn test --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master