sudo: required
services:
  - docker

before_install:
  - docker build -t liketurbo/docker-playground -f packages/frontend/Dockerfile.dev packages/frontend

script:
  - docker run liketurbo/docker-playground yarn test --coverage
