apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pccamotl-me-tls
spec:
  secretName: pccamotl-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pccamotl.me
  dnsNames:
    - pccamotl.me
    - www.pccamotl.me
  acme: 
    config: 
      - http01:
          ingressClass: nginx
        domains:
          - pccamotl.me
          - www.pccamotl.me
  
  