apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - pccamotl.me
        - www.pccamotl.me
      secretName: pccamotl-me
  rules:
    - host: pccamotl.me
      http:
        paths:
          - path: /
            backend:
              serviceName: web-service
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: server-service
              servicePort: 5000
    - host: www.pccamotl.me
      http:
        paths:
          - path: /
            backend:
              serviceName: web-service
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: server-service
              servicePort: 5000