apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: liketurbo/docker-playground-server
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: 6379
            - name: PG_USER
              value: postgres
            - name: PG_HOST
              value: postgres-service
            - name: PG_PORT
              value: 5432
            - name: PG_DATABASE
              value: postgres
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
