apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    component: web
spec:
  containers:
    - name: web
      image: liketurbo/docker-playground-web
      ports:
        - containerPort: 65535
